version: '3'
services:
  web:
    build: .
    environment:
      - SERVER_NAME=yourSurfaceWebDomainExample.com
      - ONION_ADDRESS=yourHiddenServiceURL.onion
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "service", "nginx", "status", "&&", "service", "tor", "status"]
      interval: 30s
      timeout: 10s
      retries: 3